## Broadcasting and universal functions

**Broadcasting** occurs when you apply an **universal function** to arrays that have different shapes. A **universal function** is a function that operates on **ndarrays** in an **element-wise** fashion. The operation requires that all **ndarrays** have the same shape after **broadcasting**.

## Broadcastable arrays

Arrays are broadcastable when they
1. have the **same number of dimensions** and the lenght of each dimensions is **either the same or 1**.
2. have **different number of dimensions** but satify property 1 after **prepending** dimensions of length 1 to arrays that have less dimensions.

For example:
* if **a.shape** is (5, 1) and **b.shape** is (5, 6), then **a** can be broadcasted to shape (5, 6).
* if **a.shape** is (5, 3, 2) and **b.shape** is (3, 1) then
    + **b** will be prepended a dimension of length 1 and shape becomes (1, 3, 1)
    + after prepending operation, **b** can be broadcasted to shape (5, 3, 2)

In [1]:
import numpy as np

**Example: a.shape is (5,1) and b.shape is (5, 6)**

In [2]:
a = np.array([1,2,3,4,5]).reshape((5,1))
a

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [3]:
b = np.ones(shape=(5,6))
b

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

For arithmetic operation **a + b**, **a** is broadcasted to

In [4]:
a.repeat(6, axis=1)

array([[1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5]])

In [5]:
a + b

array([[ 2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.]])

**Example, x.shape is (5,3,2) and y.shape is (3,1)**

In [6]:
x = np.ones(shape=(5,3,2))
x

array([[[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]]])

In [7]:
y = np.array([2,4,6]).reshape((3,1))
y

array([[2],
       [4],
       [6]])

**For arithmetic operation x + y, y is first broadcasted to shape (3, 2)**

In [8]:
# broadcast (3,1) to (3,2)
y.repeat(2, axis=1)

array([[2, 2],
       [4, 4],
       [6, 6]])

**then broadcased to shape (5, 3, 2)**

In [9]:
# prepend 1 to (3,2) and it becomes (1,3,2)
y.repeat(2, axis=1).reshape((1,3,2))

array([[[2, 2],
        [4, 4],
        [6, 6]]])

In [10]:
# then broadcast (1,3,2) to (5,3,2)
y.repeat(2, axis=1).reshape((1,3,2)).repeat(5, axis=0)

array([[[2, 2],
        [4, 4],
        [6, 6]],

       [[2, 2],
        [4, 4],
        [6, 6]],

       [[2, 2],
        [4, 4],
        [6, 6]],

       [[2, 2],
        [4, 4],
        [6, 6]],

       [[2, 2],
        [4, 4],
        [6, 6]]])

**`y.repeat(2, axis=1).reshape((1,3,2)).repeat(5, axis=0)` is the same as `x + y`**

In [11]:
x + y.repeat(2, axis=1).reshape((1,3,2)).repeat(5, axis=0)

array([[[ 3.,  3.],
        [ 5.,  5.],
        [ 7.,  7.]],

       [[ 3.,  3.],
        [ 5.,  5.],
        [ 7.,  7.]],

       [[ 3.,  3.],
        [ 5.,  5.],
        [ 7.,  7.]],

       [[ 3.,  3.],
        [ 5.,  5.],
        [ 7.,  7.]],

       [[ 3.,  3.],
        [ 5.,  5.],
        [ 7.,  7.]]])

In [12]:
x + y

array([[[ 3.,  3.],
        [ 5.,  5.],
        [ 7.,  7.]],

       [[ 3.,  3.],
        [ 5.,  5.],
        [ 7.,  7.]],

       [[ 3.,  3.],
        [ 5.,  5.],
        [ 7.,  7.]],

       [[ 3.,  3.],
        [ 5.,  5.],
        [ 7.,  7.]],

       [[ 3.,  3.],
        [ 5.,  5.],
        [ 7.,  7.]]])