In [1]:
import numpy as np

## Repeat `ndarray` elements along axis

### Repeat an one dimensional array by row

Two steps:
* reshape (n, ) to (1, n)
* repeat with axis=0

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [8]:
a.reshape((1,3)).repeat(4, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

### Repeat an one dimensional array by column

Two steps:
* reshape (n, ) to (n, 1)
* repeat with axis=1

In [9]:
b = np.array([2,5,3])
b

array([2, 5, 3])

In [10]:
b.reshape((3,1)).repeat(5, axis=1)

array([[2, 2, 2, 2, 2],
       [5, 5, 5, 5, 5],
       [3, 3, 3, 3, 3]])

### Repeat two dimensional array to three dimensional array

For example, repeat a.shape (3, 4) array to b.shape (4, 3, 2) array and each element of b is an a array in its first dimenion

In [11]:
a = np.array(range(12)).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Two steps:
* reshape (3,4) to (1, 3, 4)
* repeat (1, 3, 4) with axis=0

In [12]:
a.reshape((1,3,4))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [13]:
a.reshape((1,3,4)).repeat(4, axis=0)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])